spring:
  application:
    name: camunda-lafayette
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:camunda
    username: sa
    password:
    driver-class-name: org.h2.Driver

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true
    auto-deployment-enabled: true
    deployment-resource-pattern:
      - "classpath*:**/*.bpmn"
      - "classpath*:**/*.form"

logging:
  level:
    org.camunda: DEBUG
    org.springframework.web: DEBUG